
#' Estimated coefficients
#'
#' S3 methods extracting estimated coefficients for objects generated by
#' \code{robregcc}. Robust coeffcient estimate.
#'
#' @name coef_cc
#'
#' @param object Object generated by \code{robregcc}.
#' @param type 0/1 residual estimate before/after sanity check
#' @param s 0/1 no/yes 1se rule
#' @param ... additional argument
#' @return coefficient estimate
#' @importFrom stats coef
#' @export
coef_cc <- function(object, ...) {
  NextMethod("coef_cc", object, ...)
}


#' @rdname coef_cc
#' @export
coef_cc.robregcc = function(object, type = 0,  s = 1) {
  if (type == 0) {
    return(object$beta0[, s + 1])
  } else {
    return(object$betaE[, s + 1])
  }
}








#' Extract residuals estimate from the robregcc fitted object
#'
#' Robust residuals estimate
#' 
#' @name residuals
#'
#' @param object robregcc fitted onject
#' @param ... Other argumnts for future usage.
#' @return residuals estimate
#' @importFrom stats residuals
#' @rdname residuals
#' @export
residuals.robregcc <- function(object, ... ) {
  type = 0; s = 1
  if (type == 0) {
    return(object$residuals0[, s + 1])
  } else {
    return(object$residualsE[, s + 1])
  }
}

