# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  Ridge regression with compositional covariates
#'
#' @param Xt CLR transformed predictor matrix. 
#' @param y model response vector
#' @param C Subcomposition matrix
#' @param nfold number of folds for crossvalidation
#' @param nlam number of lambda to generate solution path
#' @param control controling parameter for the model 
#' @return model parameter estimate 
NULL

nzcount <- function(x) {
    .Call('_robregcc_nzcount', PACKAGE = 'robregcc', x)
}

softThres <- function(x, lambda) {
    .Call('_robregcc_softThres', PACKAGE = 'robregcc', x, lambda)
}

hardThres <- function(x, lambda) {
    .Call('_robregcc_hardThres', PACKAGE = 'robregcc', x, lambda)
}

clsq <- function(X, y, C) {
    .Call('_robregcc_clsq', PACKAGE = 'robregcc', X, y, C)
}

thresC <- function(operatr, x, lambda) {
    .Call('_robregcc_thresC', PACKAGE = 'robregcc', operatr, x, lambda)
}

classoshe <- function(Xt, y, C, we, lam0, control) {
    .Call('_robregcc_classoshe', PACKAGE = 'robregcc', Xt, y, C, we, lam0, control)
}

classol2 <- function(Xt, y, C, we, lam0, control) {
    .Call('_robregcc_classol2', PACKAGE = 'robregcc', Xt, y, C, we, lam0, control)
}

robregcc_nsp5 <- function(X, y, C, intercept, gammawt, lampath, shwt, control, ptype) {
    .Call('_robregcc_robregcc_nsp5', PACKAGE = 'robregcc', X, y, C, intercept, gammawt, lampath, shwt, control, ptype)
}

robregcc_sp5 <- function(X, y, C, paramin, control, shwt, lampath, ptype, k0, alpha) {
    .Call('_robregcc_robregcc_sp5', PACKAGE = 'robregcc', X, y, C, paramin, control, shwt, lampath, ptype, k0, alpha)
}

c_ridge2 <- function(Xt, y, C, nfold, nlam, control) {
    .Call('_robregcc_c_ridge2', PACKAGE = 'robregcc', Xt, y, C, nfold, nlam, control)
}

